log:
  output_dir: 'store/'
  file_name: 'log.json'

files:
  meta_types: ['json']
  page_types: ['md']
  default_meta_type: 'json'
  default_page_type: 'md'

templates:
  path: 'test/templates/'
  build_nav: true
  default_template: 'default.html'

input:
  input_dir: 'test/'

output:
  file_format: 'html'
  output_dir: 'dist/'
  minify_html: true

processing:
  use_nltk: false
  min_word_length: 2
  keyword_extraction: 'True'
  summary_generation: 'True'

plugins:
  path: 'plugins'
