log:
  output_dir: 'store/'
  file_name: 'log.json'

files:
  meta_types: ['json']
  page_types: ['md']

templates:
  path: 'test/templates'
  build_nav: true

output:
  file_format: 'html'
  output_dir: 'dist/'

processing:
  use_nltk: true
  min_word_length: 2
  keyword_extraction: 'True'
  summary_generation: 'True'